//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2udp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DZWIEK_CZAS_60_SCIEZKA {
            get {
                return ((string)(this["DZWIEK_CZAS_60_SCIEZKA"]));
            }
            set {
                this["DZWIEK_CZAS_60_SCIEZKA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DZWIEK_CZAS_45_SCIEZKA {
            get {
                return ((string)(this["DZWIEK_CZAS_45_SCIEZKA"]));
            }
            set {
                this["DZWIEK_CZAS_45_SCIEZKA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DZWIEK_CZAS_30_SCIEZKA {
            get {
                return ((string)(this["DZWIEK_CZAS_30_SCIEZKA"]));
            }
            set {
                this["DZWIEK_CZAS_30_SCIEZKA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DZWIEK_CZAS_15_SCIEZKA {
            get {
                return ((string)(this["DZWIEK_CZAS_15_SCIEZKA"]));
            }
            set {
                this["DZWIEK_CZAS_15_SCIEZKA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DZWIEK_CZAS_5_SCIEZKA {
            get {
                return ((string)(this["DZWIEK_CZAS_5_SCIEZKA"]));
            }
            set {
                this["DZWIEK_CZAS_5_SCIEZKA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MUZYKA_STATEK_SCIEZKA {
            get {
                return ((string)(this["MUZYKA_STATEK_SCIEZKA"]));
            }
            set {
                this["MUZYKA_STATEK_SCIEZKA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MUZYKA_WOJNA_SCIEZKA {
            get {
                return ((string)(this["MUZYKA_WOJNA_SCIEZKA"]));
            }
            set {
                this["MUZYKA_WOJNA_SCIEZKA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MUZYKA_KAPSULA_SCIEZKA {
            get {
                return ((string)(this["MUZYKA_KAPSULA_SCIEZKA"]));
            }
            set {
                this["MUZYKA_KAPSULA_SCIEZKA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MUZYKA_PALAC_SCIEZKA {
            get {
                return ((string)(this["MUZYKA_PALAC_SCIEZKA"]));
            }
            set {
                this["MUZYKA_PALAC_SCIEZKA"] = value;
            }
        }
    }
}
