//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2udp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DZWIEK_CZAS_5_PL_SCIEZKA {
            get {
                return ((string)(this["DZWIEK_CZAS_5_PL_SCIEZKA"]));
            }
            set {
                this["DZWIEK_CZAS_5_PL_SCIEZKA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MUZYKA_STATEK_PL_SCIEZKA {
            get {
                return ((string)(this["MUZYKA_STATEK_PL_SCIEZKA"]));
            }
            set {
                this["MUZYKA_STATEK_PL_SCIEZKA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MUZYKA_WOJNA_SCIEZKA {
            get {
                return ((string)(this["MUZYKA_WOJNA_SCIEZKA"]));
            }
            set {
                this["MUZYKA_WOJNA_SCIEZKA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MUZYKA_KAPSULA_SCIEZKA {
            get {
                return ((string)(this["MUZYKA_KAPSULA_SCIEZKA"]));
            }
            set {
                this["MUZYKA_KAPSULA_SCIEZKA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MUZYKA_PALAC_SCIEZKA {
            get {
                return ((string)(this["MUZYKA_PALAC_SCIEZKA"]));
            }
            set {
                this["MUZYKA_PALAC_SCIEZKA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CENTRALNE_IP {
            get {
                return ((string)(this["CENTRALNE_IP"]));
            }
            set {
                this["CENTRALNE_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WYJSCIE_EFEKT_SCIEZKA {
            get {
                return ((string)(this["WYJSCIE_EFEKT_SCIEZKA"]));
            }
            set {
                this["WYJSCIE_EFEKT_SCIEZKA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DZWIEK_CZAS_5_EN_SCIEZKA {
            get {
                return ((string)(this["DZWIEK_CZAS_5_EN_SCIEZKA"]));
            }
            set {
                this["DZWIEK_CZAS_5_EN_SCIEZKA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MUZYKA_STATEK_EN_SCIEZKA {
            get {
                return ((string)(this["MUZYKA_STATEK_EN_SCIEZKA"]));
            }
            set {
                this["MUZYKA_STATEK_EN_SCIEZKA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WERSJA_JEZYKOWA {
            get {
                return ((bool)(this["WERSJA_JEZYKOWA"]));
            }
            set {
                this["WERSJA_JEZYKOWA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TABLET_IP {
            get {
                return ((string)(this["TABLET_IP"]));
            }
            set {
                this["TABLET_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EKRANY_IP {
            get {
                return ((string)(this["EKRANY_IP"]));
            }
            set {
                this["EKRANY_IP"] = value;
            }
        }
    }
}
